FROM node:lts-alpine AS build

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npx nx build project-template

FROM nginx:stable-alpine

ENV NODE_ENV=production

WORKDIR /usr/share/nginx/html

# Remove default nginx static resources
RUN rm -rf ./*

COPY --from=build /app/dist/project-template .
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]
